// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDetQJ4BQipUjL90lvIEANeEFq_ghiVOXg",
      authDomain: "calendar-qhoang.firebaseapp.com",
      projectId: "calendar-qhoang",
      storageBucket: "calendar-qhoang.appspot.com",
      messagingSenderId: "738510436234",
      appId: "1:738510436234:web:c7e7096f8555faf7d27a73",
      measurementId: "G-K2CV2X0MM0");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoX9ewk0upqLxR0kFo8XQQkQ9wJiWrKls',
    appId: '1:736195906169:android:af5877f0b97edcd63b62a8',
    messagingSenderId: '736195906169',
    projectId: 'calendar-qhoang',
  );
}
